{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ziggle",
    "module": "vscript",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "vscript-1.3.0.jar",
          "url": "vscript-1.3.0.jar",
          "size": 1103837,
          "sha512": "b03d009ca08b92feb7185dcd4a72c9d6f675f6035681cacde8df0f6fefe6e65e19e959c9f2906b043e9973be5f5760c967c2589c6d5b817ea6e1d15fdf8c448a",
          "sha256": "e86bd07b2e8b9e5ebe15143a72e123e9b5e420453e07b3bff52f4ff9867280a5",
          "sha1": "8fcf52a06d455640bdbf2adc3385bee58d2c7a14",
          "md5": "d4f34530f3c34055e11ea9c652311d80"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "vscript-1.3.0.jar",
          "url": "vscript-1.3.0.jar",
          "size": 1103837,
          "sha512": "b03d009ca08b92feb7185dcd4a72c9d6f675f6035681cacde8df0f6fefe6e65e19e959c9f2906b043e9973be5f5760c967c2589c6d5b817ea6e1d15fdf8c448a",
          "sha256": "e86bd07b2e8b9e5ebe15143a72e123e9b5e420453e07b3bff52f4ff9867280a5",
          "sha1": "8fcf52a06d455640bdbf2adc3385bee58d2c7a14",
          "md5": "d4f34530f3c34055e11ea9c652311d80"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.ziggle",
          "module": "vscript",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "vscript-1.3.0-test-fixtures.jar",
          "url": "vscript-1.3.0-test-fixtures.jar",
          "size": 155939,
          "sha512": "44fb4ffd87a144d9fb5acb92aa01b405eae52adb0c71d39d182b336800c2b054d7d751a26f42ea699f98546a73f653cbfc6f6241db402d7ebc7b0413375af74e",
          "sha256": "e8b04b000b4512d373bb72b81a9b190bfdc4e5bda021d222479ea6c5eed9c2a5",
          "sha1": "012c88d0aa795532f5a8d4ca50439df96445c67f",
          "md5": "bb1117de72a368f9fdd69a0fce2fb0a9"
        }
      ],
      "capabilities": [
        {
          "group": "dev.ziggle",
          "name": "vscript-lang-test-fixtures",
          "version": "1.3.0"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit5"
        },
        {
          "group": "dev.ziggle",
          "module": "vscript",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit5",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "vscript-1.3.0-test-fixtures.jar",
          "url": "vscript-1.3.0-test-fixtures.jar",
          "size": 155939,
          "sha512": "44fb4ffd87a144d9fb5acb92aa01b405eae52adb0c71d39d182b336800c2b054d7d751a26f42ea699f98546a73f653cbfc6f6241db402d7ebc7b0413375af74e",
          "sha256": "e8b04b000b4512d373bb72b81a9b190bfdc4e5bda021d222479ea6c5eed9c2a5",
          "sha1": "012c88d0aa795532f5a8d4ca50439df96445c67f",
          "md5": "bb1117de72a368f9fdd69a0fce2fb0a9"
        }
      ],
      "capabilities": [
        {
          "group": "dev.ziggle",
          "name": "vscript-lang-test-fixtures",
          "version": "1.3.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vscript-1.3.0-sources.jar",
          "url": "vscript-1.3.0-sources.jar",
          "size": 548875,
          "sha512": "38ea35be2e70d0afc397fef007739362b55a91ac87394d3e814eff0cd600baf7ec458fe430fc305e68d4f6d563708768520583025f3447d6d80018374651e466",
          "sha256": "012bee5cd0653fe265c70f58dc49b5c0cc30ddec9ed7ac1695275df5254cd803",
          "sha1": "00220de507f30ed4a43e77fdeeef598dfa9d2449",
          "md5": "63b348098802bba8e3cf18b7f2481354"
        }
      ]
    }
  ]
}
