{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ziggle",
    "module": "vscript-runtime",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.ziggle",
          "module": "vscript",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "vscript-runtime-1.4.0.jar",
          "url": "vscript-runtime-1.4.0.jar",
          "size": 128319,
          "sha512": "a89d8a819248c721330d6be48c67ec287270d7397dafed37e28cfcaa944f5cd53951ebf8bb0d67c0cbf08b0f4baf9d912645f546718a41a490280c8a93e67ea4",
          "sha256": "4f50504230c3824eeb7bbca5bfd3332a532d67a2caf4307e201c730de49ee2af",
          "sha1": "f275804eb940e68c8b286ff589fc6d72a9d50ffc",
          "md5": "0b8fd331939d3f2d076ca0e4457aa835"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.ziggle",
          "module": "vscript",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "vscript-runtime-1.4.0.jar",
          "url": "vscript-runtime-1.4.0.jar",
          "size": 128319,
          "sha512": "a89d8a819248c721330d6be48c67ec287270d7397dafed37e28cfcaa944f5cd53951ebf8bb0d67c0cbf08b0f4baf9d912645f546718a41a490280c8a93e67ea4",
          "sha256": "4f50504230c3824eeb7bbca5bfd3332a532d67a2caf4307e201c730de49ee2af",
          "sha1": "f275804eb940e68c8b286ff589fc6d72a9d50ffc",
          "md5": "0b8fd331939d3f2d076ca0e4457aa835"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vscript-runtime-1.4.0-sources.jar",
          "url": "vscript-runtime-1.4.0-sources.jar",
          "size": 56052,
          "sha512": "be3691bb66dee18525e51a045906aa7bb2a0d77833f898eb859c893ac3d131f698382a853d38e7b5b1ffab80eb92e33bc9cad4b2a99de069ec5e6ee31847ef94",
          "sha256": "ae45be5cc2174f103ac416ed36796ee533938bfb3d2a0656e6057d42f91b338e",
          "sha1": "2fece1d70b9e5b554a5c968a9808bdc69fc8f9e8",
          "md5": "944202e1a08339436d41c4003d4e49d6"
        }
      ]
    }
  ]
}
