{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ziggle",
    "module": "editor-text",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.ziggle",
          "module": "vscript-runtime",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "dev.ziggle",
          "module": "editor-host",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "editor-text-1.3.0.jar",
          "url": "editor-text-1.3.0.jar",
          "size": 113828,
          "sha512": "2f8d43ae85029dddba30b5de3c4aa88f35ca0d409f98cd0fc8b37ff9a0b9385b697f082d3f41da61aee2d160d0f2b1724a5549f29981e65c63ea6d2288c6728d",
          "sha256": "a6c6347384e2eb8d70d0952a3f33cc6ca5add0896c4607a07d1d9e85f2159bac",
          "sha1": "67b7fc7c4420e1fce3853c91ede26b2bc3cc1b9f",
          "md5": "798f83867a6645e16b541b257f024f49"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.ziggle",
          "module": "vscript-ui",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "dev.ziggle",
          "module": "vscript-runtime",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "dev.ziggle",
          "module": "editor-host",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "editor-text-1.3.0.jar",
          "url": "editor-text-1.3.0.jar",
          "size": 113828,
          "sha512": "2f8d43ae85029dddba30b5de3c4aa88f35ca0d409f98cd0fc8b37ff9a0b9385b697f082d3f41da61aee2d160d0f2b1724a5549f29981e65c63ea6d2288c6728d",
          "sha256": "a6c6347384e2eb8d70d0952a3f33cc6ca5add0896c4607a07d1d9e85f2159bac",
          "sha1": "67b7fc7c4420e1fce3853c91ede26b2bc3cc1b9f",
          "md5": "798f83867a6645e16b541b257f024f49"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "editor-text-1.3.0-sources.jar",
          "url": "editor-text-1.3.0-sources.jar",
          "size": 48396,
          "sha512": "ce0d5ef69d752c74cc0c4e87a9f3a912d66788bfebd3c1919cebca1816718032dbf22fa48b88db315f6cfda8e32aa972758f2498441d20d8288c6983357a5e44",
          "sha256": "0fdbc8c87b1d18935c512b085e718b157ef4c0aaa80c3e1fa3fa7c0c277fcdb9",
          "sha1": "74c28223c430e3cf31f815ed8bfb430412430cb1",
          "md5": "c822cd11f8381cde02b48e075a886693"
        }
      ]
    }
  ]
}
