{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ziggle",
    "module": "vscript-ui",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.commonmark",
          "module": "commonmark",
          "version": {
            "requires": "0.22.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "vscript-ui-1.2.0.jar",
          "url": "vscript-ui-1.2.0.jar",
          "size": 937182,
          "sha512": "3385fa9cc555823461fcceb5d4c22bfdc19a8383b54c1aaab82d5f7a03a2658f3cab693926371e58a9bb66af16065c68060570e9a85d7ba892c665669b70f4f5",
          "sha256": "49f180d045afb360ae7d55fc786a96b613ef07f84052cb44d1813ab93d3ecf4f",
          "sha1": "73d9771cfe2d6b813527a807c93314dc695781f1",
          "md5": "e413170fada495d08b2e88f9f5b3fd94"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.commonmark",
          "module": "commonmark",
          "version": {
            "requires": "0.22.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "vscript-ui-1.2.0.jar",
          "url": "vscript-ui-1.2.0.jar",
          "size": 937182,
          "sha512": "3385fa9cc555823461fcceb5d4c22bfdc19a8383b54c1aaab82d5f7a03a2658f3cab693926371e58a9bb66af16065c68060570e9a85d7ba892c665669b70f4f5",
          "sha256": "49f180d045afb360ae7d55fc786a96b613ef07f84052cb44d1813ab93d3ecf4f",
          "sha1": "73d9771cfe2d6b813527a807c93314dc695781f1",
          "md5": "e413170fada495d08b2e88f9f5b3fd94"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vscript-ui-1.2.0-sources.jar",
          "url": "vscript-ui-1.2.0-sources.jar",
          "size": 878987,
          "sha512": "d9f33ccf7c64a574ce4c085e331f6d69d5c4417d1c42fb013705de3807ab1098f620912dffb385584244b22008e0aa43ec62e0131c53ac193622664f3d1aa3d9",
          "sha256": "86f55e9b1f54d9b6f933dd94da757592c751a2570fb2ba3872ddb3e4e5cedd9d",
          "sha1": "a911a93ffd4612d0559e239650bdf4e3207d860b",
          "md5": "ffdb5e080ad2167e268075f54a2fe684"
        }
      ]
    }
  ]
}
