{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ziggle",
    "module": "vscript-gradle",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "vscript-gradle-1.3.0.jar",
          "url": "vscript-gradle-1.3.0.jar",
          "size": 21950,
          "sha512": "b81c119b61ea4a4f89095d9dc7494f959a11a744f1e929b56a89cf4be80ad95cb8c8899a073ecc707c569cc21a7b70f42874907fb53e73118b4d110dda9d62cc",
          "sha256": "25d35ab60570dd8647f853d6a8d5768091fbdb17d6408ee5e137a366774c57f2",
          "sha1": "9ad987700e5a00a33076a3b1746a5aa29241ed62",
          "md5": "e354d7183280aa2bceaea569862586b2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "vscript-gradle-1.3.0.jar",
          "url": "vscript-gradle-1.3.0.jar",
          "size": 21950,
          "sha512": "b81c119b61ea4a4f89095d9dc7494f959a11a744f1e929b56a89cf4be80ad95cb8c8899a073ecc707c569cc21a7b70f42874907fb53e73118b4d110dda9d62cc",
          "sha256": "25d35ab60570dd8647f853d6a8d5768091fbdb17d6408ee5e137a366774c57f2",
          "sha1": "9ad987700e5a00a33076a3b1746a5aa29241ed62",
          "md5": "e354d7183280aa2bceaea569862586b2"
        }
      ]
    }
  ]
}
