{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ziggle",
    "module": "vscript-gradle",
    "version": "1.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "vscript-gradle-1.3.1.jar",
          "url": "vscript-gradle-1.3.1.jar",
          "size": 21951,
          "sha512": "cef18ece7b460db2a5429ac9fd7d5b22cea1fbbd138d622c7d7db76b73c7487a2be9e883bf1fc2b212e5777405ddd97399dfac00fccb08fc57b7287a2072582a",
          "sha256": "12d8884a32ee0149414e5a0f4733a979ebc17d7ba3600e77780604706054189f",
          "sha1": "962b5d3248d5d776ee83f0e24584e65ae2e47414",
          "md5": "9ab126ec455e34b64f952547aba16a1c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "vscript-gradle-1.3.1.jar",
          "url": "vscript-gradle-1.3.1.jar",
          "size": 21951,
          "sha512": "cef18ece7b460db2a5429ac9fd7d5b22cea1fbbd138d622c7d7db76b73c7487a2be9e883bf1fc2b212e5777405ddd97399dfac00fccb08fc57b7287a2072582a",
          "sha256": "12d8884a32ee0149414e5a0f4733a979ebc17d7ba3600e77780604706054189f",
          "sha1": "962b5d3248d5d776ee83f0e24584e65ae2e47414",
          "md5": "9ab126ec455e34b64f952547aba16a1c"
        }
      ]
    }
  ]
}
