{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.ziggle",
    "module": "vscript-gradle",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "vscript-gradle-1.4.0.jar",
          "url": "vscript-gradle-1.4.0.jar",
          "size": 21949,
          "sha512": "847e8393b7cda1f54b19ce5e492184bc5e87525760bc4cbff2d09ebbe463fe66cec39b4f14f9139642a17c246931402ffd5a3c60d7a50193cc244a36d5caf19a",
          "sha256": "d034638c74e7925a41237111d39f3852b5466c9c5c0c80ecfd39afb715e23a81",
          "sha1": "6b566b6f57b0467637f8d7cdedd5b9b784d33a2e",
          "md5": "32df6726cef6cc20ece54cb5811a6a8b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "vscript-gradle-1.4.0.jar",
          "url": "vscript-gradle-1.4.0.jar",
          "size": 21949,
          "sha512": "847e8393b7cda1f54b19ce5e492184bc5e87525760bc4cbff2d09ebbe463fe66cec39b4f14f9139642a17c246931402ffd5a3c60d7a50193cc244a36d5caf19a",
          "sha256": "d034638c74e7925a41237111d39f3852b5466c9c5c0c80ecfd39afb715e23a81",
          "sha1": "6b566b6f57b0467637f8d7cdedd5b9b784d33a2e",
          "md5": "32df6726cef6cc20ece54cb5811a6a8b"
        }
      ]
    }
  ]
}
